Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    PackageArgs:
    SaveRepos:  False
    Timezone: America/New_York
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 3000
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - MeeGo X Window System

NETBOOK:
    PartSize: 3000
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    PostScripts:
        - cleanup
        - flash
    Groups:
        - X for Netbooks
        - Virtual Machine Support
        - Printing
        - Games
    Kernel: kernel-netbook
    Repos:
        - adobe
        - meego-core-1.0
        - meego-netbook-1.0
        - meego-extra-1.0
        - meego-non-oss-1.0
    PostScripts:
        - prelink
        - cleanup
    ExtraPackages:
        - gdb
        - flash-plugin
        - adobe-release
        - -google-chrome

Configurations:
    -   Name: MeeGo Netbook/Nettop 1.0 
        Active: True
        Baseline: 1.0
        Platform: NETBOOK
        Desktop: moblin
        FileName: netbook
        Groups:
            - MeeGo Netbook Desktop
        Repos:
            - meego-core-1.0
            - meego-netbook-1.0
