# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 06:03


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('apiurl', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=60, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.BooleanField(default=False)),
                ('test_results_url', models.TextField(blank=True, null=True)),
                ('image_type', models.CharField(max_length=10)),
                ('tokenmap', models.CharField(blank=True, max_length=1000)),
                ('arch', models.CharField(max_length=10)),
                ('overlay', models.CharField(blank=True, max_length=500)),
                ('extra_repos', models.CharField(blank=True, max_length=800)),
                ('kickstart', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default=b'IN QUEUE', max_length=30)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('files_url', models.CharField(blank=True, max_length=500)),
                ('logfile_url', models.CharField(blank=True, max_length=500)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('pp_args', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('pdef', models.TextField()),
                ('argname', models.CharField(blank=True, max_length=40)),
                ('triggers', models.ManyToManyField(to='app.JobState')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('handle_launch', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('default', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagejob',
            name='post_processes',
            field=models.ManyToManyField(to='app.PostProcess'),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Queue'),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='imagejob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
